name: Build one

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      target_os:
        description: Target OS
        type: choice
        options:
          - linux
          - mac
          - win
      target_cpu:
        description: Target CPU
        type: choice
        options:
          - arm64
          - x64
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false
      build_type:
        description: Build type
        type: choice
        default: static
        options:
          - static
          - shared

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ${{ github.event.inputs.target_os }}
      target_cpu: ${{ github.event.inputs.target_cpu }}
      build_type: ${{ github.event.inputs.build_type }}
